<?php 
		$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();  
		$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
		$connection = $resource->getConnection();
		$tableName = $resource->getTableName('backinstock');

		$sql = "SELECT p_id,newdate FROM ".$tableName." ";		
		 $resultAll = $connection->fetchAll($sql);		 
		 foreach($resultAll as $result ){
		  $productid= $result['p_id'];
	     $product = $objectManager->create('Magento\Catalog\Model\Product')->load($productid);       				
		$_imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Helper\Image');
		$imageUrl = $_imageHelper->init($product, 'small_image', ['type'=>'small_image'])->keepAspectRatio(true)->resize('268','268')->getUrl();
		?>
		<img src="<?php echo $imageUrl;?>"/>
		  <?php echo $product->getName(); ?>
		  <div class="c">
             <img class="item" src="<?php echo $imageUrl;?>">
             <img class="item" src="https://unsplash.it/730/454?image=448">
             <img class="item" src="https://unsplash.it/730/454?image=447">
             <img class="item" src="https://unsplash.it/730/454?image=505">
             <img class="item" src="https://unsplash.it/730/454?image=506">
             <img class="item" src="https://unsplash.it/730/454?image=503">
        </div>

		<?php 	}?>