<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl      = $storeManager->getStore()->getBaseUrl();?>

<div class="search-place-order">
  <a href="<?php echo $baseUrl.'customsearch'?>">Place Order</a>
   <h2>Back in Stock</h2>
</div><!-- search-place-order -->
		<?php 
		
		$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();  
		$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
		$connection = $resource->getConnection();
		$tableName = $resource->getTableName('backinstock');
		

		//$sql = "SELECT p_id,newdate FROM ".$tableName." ";	
		$sql = "SELECT * FROM ".$tableName." WHERE `newdate` >= DATE_SUB(CURDATE(),INTERVAL 7 DAY) and oldqty!= newqty";
		
		$resultAll = $connection->fetchAll($sql);
		//print_r($resultAll);die('testws');
		
		$saleableProductArr = array();
		foreach($resultAll as $result ){
			$productid = $result['p_id'];
			$product = $objectManager->create('Magento\Catalog\Model\Product')->load($productid); 
			if($product->isSaleable()){
				array_push($saleableProductArr,$product->getId());	
			}
		}
		?>
		
		<?php if(!empty($saleableProductArr)){ ?>
		<div id="owl-demo">		 
		 <?php 
		 $i=1;
		 
		foreach($saleableProductArr as $result ){
			//$productid = $result['p_id'];
			$product = $objectManager->create('Magento\Catalog\Model\Product')->load($result); 
			
			$_imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Helper\Image');
			$imageUrl = $_imageHelper->init($product, 'small_image', ['type'=>'small_image'])->keepAspectRatio(true)->resize('268','268')->getUrl();
			$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
			$product->isSaleable();
			
		?>
		      
           <?php if($i%4==1){ ?>
			<div class="item">
		   <?php } ?>
				<div class="item-custom">
					<img src="<?php echo $imageUrl;?>" alt="Owl Image">
					<p><a href=""><?php echo $product->getName(); ?></a></p>
				</div><!-- item-custom -->
		   <?php if($i%4==0){ ?>
			</div><!-- item -->
		   <?php } ?>
		<?php $i++; ?>
		
		 <?php } ?>
		</div>
		<?php }else{ ?>
		<div class="item-custom">No Record Found.</div>
		<?php } ?>
		
		
		
		<script type="text/javascript">
          require(['jquery','OwlCarousel'],function($){
          $(window).load(function() {
           $("#owl-demo").owlCarousel({
                   navigation: false, // Show next and prev buttons
                   navText:["<",">"], //show prev next
                   loop: true,
                   autoplay: true, //Set AutoPlay  
                   autoplayHoverPause: true, //stop when mouse on carousel
                   items : 1,
                   autoPlay : 5000,
                   pagination:false
         });
       });
   });
</script>