<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>



<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>


		    <?php
				$_productCollection = $block->getLoadedProductCollection();
				$_helper = $this->helper('Magento\Catalog\Helper\Output');
				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
				$baseUrl= $storeManager->getStore()->getBaseUrl();								
				$customerSession = $objectManager->create('Magento\Customer\Model\Session');
				?>

				<?php if (!$customerSession->isLoggedIn()) {				  
				echo ("<script LANGUAGE='JavaScript'>          
				window.location.href = '$baseUrl';
				</script>"); 
                } ?>


<?php if (!$_productCollection->count()): ?>
  
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
	

    <table class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>" border="1">
		    
			<tr>
			<th>Picture</th>
			<th>Item</th> 
			<th>Description</th>
			<th>Stock Status</th>
			<th>Next ETA</th> 
			<th>Notify</th>
			<th>Qty</th>
		  </tr>
	   
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            
			<?php foreach ($_productCollection as $_product): ?>
			<tr>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
				
                
                    <td>
						<?php
							$productImage = $block->getImage($_product, $image);
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
						?>
						<?php // Product Image ?>
						<a href="#" class="product photo product-item-photo" tabindex="-1">
							<?= $productImage->toHtml() ?>
						</a>
					</td>

					<td>
					<?php
						echo $_product->getSku();
						?>
					</td>
					<td>
						
						<?php
						$_productNameStripped = $block->stripTags($_product->getName(), null, true);
						?>
						<strong class="product name product-item-name">						
						<?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
						
						</strong>

					</td>
					<td>
                        
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_product->getSku() ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <!--<button type="submit"
                                                    title="<? //= $block->escapeHtml(__('In stock')) ?>"
                                                    class="action tocart primary">
                                                <span><? //= /* @escapeNotVerified */ __('In stock') ?></span>
                                            </button>-->
											<span><?= /* @escapeNotVerified */ __('In stock') ?></span>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                              
                            </div>
                            
					</td>
							<!--ETA-->
					<td>
							<?php if(!empty($_product->getEta())):?>
							<?php echo  substr($_product->getEta(), 0, 10) . '<br>'; ?>
                            <?php endif;?>
					</td>
							<!--ETA code end here -->
							
							
							 <!-- Notification code-->
					<td>
						<?php if (!$_product->isSaleable()): ?>
								<div class="block newsletter stocknotification">
												
									<?php 
									
									$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
									$baseUrl= $storeManager->getStore()->getBaseUrl();								
									$customerSession = $objectManager->create('Magento\Customer\Model\Session');
									?>
									<div class="content">
									<form class="form subscribe"
									novalidate
									action="<?php echo $baseUrl; ?>stocknotification/index/signup/product_id/<?php echo $_product->getId()?>"
									method="post"
									data-mage-init='{"validation": {"errorClass": "mage-error"}}'
											id="stocknotification-validate-email">
											<div class="field newsletter">
											<div class="control">
											<input style = "display:none" name="email" type="email" id="email"
											value="<?php if ($customerSession->isLoggedIn()) {
											  echo  $customerSession->getCustomer()->getEmail(); // get Email
											  }?>"
											placeholder="<?php echo __('Enter your e-mail') ?>"
											data-validate="{required:true, 'validate-email':true}"/>
											</div>
											</div>
											<div class="actions">
											<button class="action subscribe primary">
											<?php echo __('Notify Me') ?>
											</button>
											</div>
									</form>
									</div>
								</div>
							<?php endif;?> <!-- Notification code end here-->
					</td>
							<!--qty-->
					<td>
							<?php 		
							    							
								$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
								echo $StockState->getStockQty($_product->getId(), $_product->getStore()->getWebsiteId());
							?>
					</td>
							<!--qty end here-->
							
                      
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            </tr>
			<?php endforeach; ?>
			
        </ol>
    </table>
	<div class="img-block-cls">		
		<?php echo $block->getLayout()->createBlock('Allin\Customslider\Block\Index\Index')->setTemplate('Allin_Customslider::customslider_index_index.phtml')->toHtml();?>
	</div>

	
	
	
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>


<script type="text/javascript">
require(['jquery'],function($){
	
	$( "div.img-block-cls" ).insertAfter( "div.sidebar.sidebar-additional" );

});
</script>
